### ISSUE TITLE
Add link to original discussion of this package

### ISSUE THREAD

**Issue by scottyhq** [stactools-packages/sentinel1#1]
Just linking to the original pull request for this package https://github.com/stac-utils/stactools/pull/84 . 

There is useful discussion there about developing a subpackage for stactools, and decisions that were made about the current implementation.

**Comment by gadomski** [comment]
The implementation stuff should probably get pulled to either README or a design decision document in this repo I reckon.

**Comment by scottyhq** [comment]
closed by #2
