### ISSUE TITLE
Cant Install both Sentinel-1 and Sentinel-2 subpackages

### ISSUE THREAD

**Issue by hortonhearsadan** [stactools-packages/sentinel1#19]
sentinel-2 v3.0 uses stactools 0.3.0 but the latest sentinel-1 package still uses v0.2.1 and so i cant use them both on the same env.

are there plans to update the stactools version?

**Comment by wildintellect** [comment]
This should no longer be an issue the version has been updated (not in the released version yet).
https://github.com/stactools-packages/sentinel1/blob/1891f462007c2acfaa39a0c96920db9275ec7f52/setup.cfg#L33

**Comment by gadomski** [comment]
Yup, confirmed that this problem is solved:

```shell
$ pip uninstall -y stactools-sentinel1 stactools-sentinel2 && \
        pip install stactools-sentinel1 stactools-sentinel2 && \
        echo "import stactools.sentinel1\nprint(stactools.sentinel1.__version__)" | python && \
        echo "import stactools.sentinel2\nprint(stactools.sentinel2.__version__)" | python
... snip ...
Successfully installed stactools-sentinel1-0.3.0 stactools-sentinel2-0.2.0
0.3.0
0.2.0
```
