### ISSUE TITLE
Adding repository secrets

### ISSUE THREAD

**Issue by scottyhq** [stactools-packages/sentinel1#4]
@gadomski - I currently have write permissions in this repository, but no access to repository settings. Is it possible to grant that access as well? I could then add a token with permissions for this workflow https://github.com/stactools-packages/sentinel1/blob/main/.github/workflows/sync-template.yml , which fails due to incorrect permissions with the default token https://github.com/stactools-packages/sentinel1/runs/3128144521?check_suite_focus=true

**Comment by gadomski** [comment]
Yup, just granted you admin, LMK if you need anything else!
