### ISSUE TITLE
Missing Support for SLC Products in Latest stactools Release for Sentinel-1

### ISSUE THREAD

**Issue by simonvb00** [stactools-packages/sentinel1#59]
Hi everyone! The latest release of this project was in may 2023. The support for SLC products seems to have been added somewhere in October (according to the history of __init__.py in the slc sub-directory). Because of this, the latest release of the stactools package for Sentinel-1 (version 0.7.1) lacks support for SLC products. When will the new version with support for SLC products be released?

**Comment by gadomski** [comment]
Hey, thanks for the ping. We can get a release out — I'll see if I can get to it today/this weekend.

**Comment by gadomski** [comment]
@simonvb00 done! https://pypi.org/project/stactools-sentinel1/0.8.0/
